/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ABrExpExpression extends PExpression
{
    private final LinkedList _moreValues_ = new TypedLinkedList(new MoreValues_Cast());

    public ABrExpExpression()
    {
    }

    public ABrExpExpression(
        List _moreValues_)
    {
        {
            this._moreValues_.clear();
            this._moreValues_.addAll(_moreValues_);
        }

    }
    public Object clone()
    {
        return new ABrExpExpression(
            cloneList(_moreValues_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABrExpExpression(this);
    }

    public LinkedList getMoreValues()
    {
        return _moreValues_;
    }

    public void setMoreValues(List list)
    {
        _moreValues_.clear();
        _moreValues_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_moreValues_);
    }

    void removeChild(Node child)
    {
        if(_moreValues_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for(ListIterator i = _moreValues_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class MoreValues_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PMoreValues node = (PMoreValues) o;

            if((node.parent() != null) &&
                (node.parent() != ABrExpExpression.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != ABrExpExpression.this))
            {
                node.parent(ABrExpExpression.this);
            }

            return node;
        }
    }
}
