/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class ACommaIdAsId extends PCommaIdAsId
{
    private TId _id_;
    private final LinkedList _asIdentifier_ = new TypedLinkedList(new AsIdentifier_Cast());

    public ACommaIdAsId()
    {
    }

    public ACommaIdAsId(
        TId _id_,
        List _asIdentifier_)
    {
        setId(_id_);

        {
            this._asIdentifier_.clear();
            this._asIdentifier_.addAll(_asIdentifier_);
        }

    }
    public Object clone()
    {
        return new ACommaIdAsId(
            (TId) cloneNode(_id_),
            cloneList(_asIdentifier_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACommaIdAsId(this);
    }

    public TId getId()
    {
        return _id_;
    }

    public void setId(TId node)
    {
        if(_id_ != null)
        {
            _id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _id_ = node;
    }

    public LinkedList getAsIdentifier()
    {
        return _asIdentifier_;
    }

    public void setAsIdentifier(List list)
    {
        _asIdentifier_.clear();
        _asIdentifier_.addAll(list);
    }

    public String toString()
    {
        return ""
            + toString(_id_)
            + toString(_asIdentifier_);
    }

    void removeChild(Node child)
    {
        if(_id_ == child)
        {
            _id_ = null;
            return;
        }

        if(_asIdentifier_.remove(child))
        {
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        if(_id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator i = _asIdentifier_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

    }

    private class AsIdentifier_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PAsIdentifier node = (PAsIdentifier) o;

            if((node.parent() != null) &&
                (node.parent() != ACommaIdAsId.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != ACommaIdAsId.this))
            {
                node.parent(ACommaIdAsId.this);
            }

            return node;
        }
    }
}
