/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import java.util.*;
import minipython.analysis.*;

public final class AIntegerNumber extends PNumber
{
    private final LinkedList _sign_ = new TypedLinkedList(new Sign_Cast());
    private TInteger _integer_;

    public AIntegerNumber()
    {
    }

    public AIntegerNumber(
        List _sign_,
        TInteger _integer_)
    {
        {
            this._sign_.clear();
            this._sign_.addAll(_sign_);
        }

        setInteger(_integer_);

    }
    public Object clone()
    {
        return new AIntegerNumber(
            cloneList(_sign_),
            (TInteger) cloneNode(_integer_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntegerNumber(this);
    }

    public LinkedList getSign()
    {
        return _sign_;
    }

    public void setSign(List list)
    {
        _sign_.clear();
        _sign_.addAll(list);
    }

    public TInteger getInteger()
    {
        return _integer_;
    }

    public void setInteger(TInteger node)
    {
        if(_integer_ != null)
        {
            _integer_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        _integer_ = node;
    }

    public String toString()
    {
        return ""
            + toString(_sign_)
            + toString(_integer_);
    }

    void removeChild(Node child)
    {
        if(_sign_.remove(child))
        {
            return;
        }

        if(_integer_ == child)
        {
            _integer_ = null;
            return;
        }

    }

    void replaceChild(Node oldChild, Node newChild)
    {
        for(ListIterator i = _sign_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set(newChild);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(_integer_ == oldChild)
        {
            setInteger((TInteger) newChild);
            return;
        }

    }

    private class Sign_Cast implements Cast
    {
        public Object cast(Object o)
        {
            PSign node = (PSign) o;

            if((node.parent() != null) &&
                (node.parent() != AIntegerNumber.this))
            {
                node.parent().removeChild(node);
            }

            if((node.parent() == null) ||
                (node.parent() != AIntegerNumber.this))
            {
                node.parent(AIntegerNumber.this);
            }

            return node;
        }
    }
}
