/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TDif extends Token
{
    public TDif()
    {
        super.setText("!=");
    }

    public TDif(int line, int pos)
    {
        super.setText("!=");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TDif(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDif(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TDif text.");
    }
}
