/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

public final class TImp extends Token
{
    public TImp()
    {
        super.setText("import");
    }

    public TImp(int line, int pos)
    {
        super.setText("import");
        setLine(line);
        setPos(pos);
    }

    public Object clone()
    {
      return new TImp(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTImp(this);
    }

    public void setText(String text)
    {
        throw new RuntimeException("Cannot change TImp text.");
    }
}
