/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.parser;

import minipython.node.*;
import minipython.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    public void caseTTab(TTab node)
    {
        index = 0;
    }

    public void caseTPlus(TPlus node)
    {
        index = 1;
    }

    public void caseTMinus(TMinus node)
    {
        index = 2;
    }

    public void caseTMult(TMult node)
    {
        index = 3;
    }

    public void caseTDmult(TDmult node)
    {
        index = 4;
    }

    public void caseTMineq(TMineq node)
    {
        index = 5;
    }

    public void caseTDiveq(TDiveq node)
    {
        index = 6;
    }

    public void caseTDiv(TDiv node)
    {
        index = 7;
    }

    public void caseTDot(TDot node)
    {
        index = 8;
    }

    public void caseTEq(TEq node)
    {
        index = 9;
    }

    public void caseTDeq(TDeq node)
    {
        index = 10;
    }

    public void caseTExclam(TExclam node)
    {
        index = 11;
    }

    public void caseTDictt(TDictt node)
    {
        index = 12;
    }

    public void caseTDef(TDef node)
    {
        index = 13;
    }

    public void caseTLogicPlus(TLogicPlus node)
    {
        index = 14;
    }

    public void caseTLPar(TLPar node)
    {
        index = 15;
    }

    public void caseTRPar(TRPar node)
    {
        index = 16;
    }

    public void caseTLBr(TLBr node)
    {
        index = 17;
    }

    public void caseTRBr(TRBr node)
    {
        index = 18;
    }

    public void caseTComma(TComma node)
    {
        index = 19;
    }

    public void caseTQmark(TQmark node)
    {
        index = 20;
    }

    public void caseTGqmark(TGqmark node)
    {
        index = 21;
    }

    public void caseTIf(TIf node)
    {
        index = 22;
    }

    public void caseTElif(TElif node)
    {
        index = 23;
    }

    public void caseTElse(TElse node)
    {
        index = 24;
    }

    public void caseTWhile(TWhile node)
    {
        index = 25;
    }

    public void caseTFor(TFor node)
    {
        index = 26;
    }

    public void caseTFrom(TFrom node)
    {
        index = 27;
    }

    public void caseTImp(TImp node)
    {
        index = 28;
    }

    public void caseTAssert(TAssert node)
    {
        index = 29;
    }

    public void caseTAs(TAs node)
    {
        index = 30;
    }

    public void caseTPrint(TPrint node)
    {
        index = 31;
    }

    public void caseTReturn(TReturn node)
    {
        index = 32;
    }

    public void caseTIn(TIn node)
    {
        index = 33;
    }

    public void caseTLess(TLess node)
    {
        index = 34;
    }

    public void caseTGreat(TGreat node)
    {
        index = 35;
    }

    public void caseTDif(TDif node)
    {
        index = 36;
    }

    public void caseTTrue(TTrue node)
    {
        index = 37;
    }

    public void caseTSemi(TSemi node)
    {
        index = 38;
    }

    public void caseTFalse(TFalse node)
    {
        index = 39;
    }

    public void caseTQuote(TQuote node)
    {
        index = 40;
    }

    public void caseTId(TId node)
    {
        index = 41;
    }

    public void caseTFloat(TFloat node)
    {
        index = 42;
    }

    public void caseTInteger(TInteger node)
    {
        index = 43;
    }

    public void caseTString(TString node)
    {
        index = 44;
    }

    public void caseEOF(EOF node)
    {
        index = 45;
    }
}
